cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: android

jdk:
  - oraclejdk8

# todo: remove once https://github.com/travis-ci/travis-ci/issues/8874 is resolved
before_install:
  - yes | sdkmanager "platforms;android-29"

android:
  components:
    - tools
    - build-tools-29.0.2
    - android-29
    - platform-tools

    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository

branches:
  only:
    - master
    # Match semver branch names like 1.0.0, 1.0.0-rc.2, etc.:
    - /^\d+\.\d+\.\d+(?:-rc\.\d+)?$/

script: ./travis-build.sh
